In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('final_stock_consolidated.csv')
df.head()

Date    Open    High     Low   Close  Volume  OpenInt stock_ticker
0  1970-01-02  2.2972  2.3178  2.2972  2.2972   26437        0           AA
1  1970-01-05  2.2972  2.2972  2.2544  2.2759   29887        0           AA
2  1970-01-06  2.2759  2.2759  2.2342  2.2342  106900        0           AA
3  1970-01-07  2.2342  2.2342  2.2342  2.2342   85061        0           AA
4  1970-01-08  2.2342  2.2342  2.2139  2.2139   66669        0           AA

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3526116 entries, 0 to 3526115
Data columns (total 8 columns):
 #   Column        Dtype         
---  ------        -----         
 0   Date          datetime64[ns]
 1   Open          float64       
 2   High          float64       
 3   Low           float64       
 4   Close         float64       
 5   Volume        int64         
 6   OpenInt       int64         
 7   stock_ticker  object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 215.2+ MB


In [ ]:
df = df.sort_values(by='Date')
df.head()


Date    Open    High  ...   Volume  OpenInt  stock_ticker
2004875 1962-01-02  6.4130  6.4130  ...   467056        0           IBM
1770244 1962-01-02  0.6277  0.6362  ...  2575579        0            GE
2004876 1962-01-03  6.3378  6.3963  ...   350294        0           IBM
1770245 1962-01-03  0.6201  0.6201  ...  1764749        0            GE
2004877 1962-01-04  6.3963  6.3963  ...   314365        0           IBM

[5 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_stock = label_encoder.fit_transform(df['stock_ticker'])

In [ ]:
df['stock_ticker'] = label_stock
df.head()


Date    Open    High  ...   Volume  OpenInt  stock_ticker
2004875 1962-01-02  6.4130  6.4130  ...   467056        0           461
1770244 1962-01-02  0.6277  0.6362  ...  2575579        0           422
2004876 1962-01-03  6.3378  6.3963  ...   350294        0           461
1770245 1962-01-03  0.6201  0.6201  ...  1764749        0           422
2004877 1962-01-04  6.3963  6.3963  ...   314365        0           461

[5 rows x 8 columns]

In [ ]:
df['Date'] = df['Date'].values.astype(np.int64) 
df.head()


Date    Open    High  ...   Volume  OpenInt  stock_ticker
2004875 -252374400000000000  6.4130  6.4130  ...   467056        0           461
1770244 -252374400000000000  0.6277  0.6362  ...  2575579        0           422
2004876 -252288000000000000  6.3378  6.3963  ...   350294        0           461
1770245 -252288000000000000  0.6201  0.6201  ...  1764749        0           422
2004877 -252201600000000000  6.3963  6.3963  ...   314365        0           461

[5 rows x 8 columns]

In [ ]:
df = df.drop(df.columns[[2,3,4,5,6]], axis=1)

In [ ]:
training_set = df.iloc[:2500000, ].values
test_set = df.iloc[2500000:, ].values
test_data = df.iloc[2500000:, ]
training_data = df.iloc[:2500000, ]

In [ ]:
test_data

Date      Open  stock_ticker
991295   1330041600000000000    4.4505           243
936184   1330041600000000000   70.3270           231
422306   1330041600000000000   34.7080            98
3447144  1330041600000000000   50.5840           712
430025   1330041600000000000    4.5600           100
...                      ...       ...           ...
1696943  1510272000000000000  216.8900           406
1701977  1510272000000000000   33.3700           407
1705178  1510272000000000000  120.6000           408
1662247  1510272000000000000   40.8600           400
3526115  1510272000000000000   44.1000           725

[1026116 rows x 3 columns]

In [ ]:
test_set_stock = test_data['Open'].values

In [ ]:
test_set_stock

array([  4.4505,  70.327 ,  34.708 , ..., 120.6   ,  40.86  ,  44.1   ])

In [ ]:
training_data.head()

Date    Open  stock_ticker
2004875 -252374400000000000  6.4130           461
1770244 -252374400000000000  0.6277           422
2004876 -252288000000000000  6.3378           461
1770245 -252288000000000000  0.6201           422
2004877 -252201600000000000  6.3963           461

In [ ]:
training_set

array([[-2.5237440e+17,  6.4130000e+00,  4.6100000e+02],
       [-2.5237440e+17,  6.2770000e-01,  4.2200000e+02],
       [-2.5228800e+17,  6.3378000e+00,  4.6100000e+02],
       ...,
       [ 1.3300416e+18,  2.0710000e+01,  6.8200000e+02],
       [ 1.3300416e+18,  5.9326000e+01,  2.3000000e+02],
       [ 1.3300416e+18,  7.6200000e+00,  6.1800000e+02]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0, 1))

training_set_scaled = sc.fit_transform(training_set)

training_set_scaled.shape

(2500000, 3)

In [ ]:
training_set_scaled.shape[0]

2500000

In [ ]:
X_train = []
y_train = []
for i in range(60, 2500000):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train


array([[0.00000000e+00, 0.00000000e+00, 5.46000546e-05, ...,
        2.07480207e-03, 2.23860224e-03, 2.23860224e-03],
       [0.00000000e+00, 5.46000546e-05, 5.46000546e-05, ...,
        2.23860224e-03, 2.23860224e-03, 2.29320229e-03],
       [5.46000546e-05, 5.46000546e-05, 1.09200109e-04, ...,
        2.23860224e-03, 2.29320229e-03, 2.29320229e-03],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [ ]:
X_train.shape[1]

60

In [ ]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_train.shape
y_train.shape

(2499940,)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout


In [ ]:
model = Sequential()
#Adding the first LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
model.add(Dropout(0.2))
# Adding a second LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a third LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a fourth LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50))
model.add(Dropout(0.2))
# Adding the output layer
model.add(Dense(units = 1))

# Compiling the RNN
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Fitting the RNN to the Training set
model.fit(X_train, y_train, epochs = 10, batch_size = 64)

Epoch 1/10
39062/39062 [==============================] - 555s 14ms/step - loss: 5.3941e-04
Epoch 2/10
39062/39062 [==============================] - 545s 14ms/step - loss: 2.1715e-04
Epoch 3/10
39062/39062 [==============================] - 551s 14ms/step - loss: 2.0785e-04
Epoch 4/10
39062/39062 [==============================] - 566s 15ms/step - loss: 2.0305e-04
Epoch 5/10
39062/39062 [==============================] - 554s 14ms/step - loss: 1.9956e-04
Epoch 6/10
39062/39062 [==============================] - 530s 14ms/step - loss: 1.9707e-04
Epoch 7/10
39062/39062 [==============================] - 528s 14ms/step - loss: 1.9656e-04
Epoch 8/10
39062/39062 [==============================] - 543s 14ms/step - loss: 1.9413e-04
Epoch 9/10
39062/39062 [==============================] - 538s 14ms/step - loss: 1.9364e-04
Epoch 10/10
39062/39062 [==============================] - 527s 13ms/step - loss: 1.9245e-04


In [ ]:
test_set_scaled = sc.fit_transform(test_set)
test_set_scaled.shape
# test_set.shape


(1026116, 3)

In [ ]:
dataset_total = pd.concat((training_data, test_data), axis = 0)


In [ ]:
dataset_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3526116 entries, 2004875 to 3526115
Data columns (total 3 columns):
 #   Column        Dtype  
---  ------        -----  
 0   Date          int64  
 1   Open          float64
 2   stock_ticker  int64  
dtypes: float64(1), int64(2)
memory usage: 107.6 MB


In [ ]:
inputs = dataset_total[len(dataset_total) - len(test_data) - 60:].values
print(len(dataset_total))
print(len(test_data) - 60)

3526116
1026056


In [ ]:
 inputs = inputs.reshape(-1,1)
 inputs.shape

(3078528, 1)

In [ ]:

inputs = sc.transform(inputs)
X_test = []
for i in range(60, 1026176):
    X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = model.predict(X_test)

predicted_stock_price

array([[0.03348494],
       [0.03348511],
       [0.03348505],
       ...,
       [0.03348505],
       [0.033485  ],
       [0.03348511]], dtype=float32)

In [ ]:
X_test.shape

(1026116, 60, 1)

In [ ]:
# predicted_stock_price.shape
sc.inverse_transform(predicted_stock_price[:, [0]])
# predicted_stock_price = sc.inverse_transform(predicted_stock_price)

array([[0.2525738 ],
       [0.26184094],
       [0.25949097],
       ...,
       [0.26596016],
       [0.2587273 ],
       [0.26828575]], dtype=float32)

In [ ]:
predicted_stock_price
# sc.inverse_transform?
# predicted_stock_price = sc.inverse_transform(predicted_stock_price)

array([[0.2525738 ],
       [0.26184094],
       [0.25949097],
       ...,
       [0.26596016],
       [0.2587273 ],
       [0.26828575]], dtype=float32)

In [ ]:
test_set_stock1 = test_set_stock.reshape(-1,1)

test_set_scaled = sc.fit_transform(test_set_stock1)

test_set_scaled

array([[1.46426968e-05],
       [2.55764960e-04],
       [1.25391703e-04],
       ...,
       [4.39775033e-04],
       [1.47909356e-04],
       [1.59768458e-04]])

In [ ]:
test_set_scaled.shape

(1026116, 1)

In [ ]:
 from sklearn.metrics import mean_squared_error


In [ ]:
# trainScore = np.sqrt(mean_squared_error(test_set_stock, predicted_stock_price))
# print('Train Score: %.2f RMSE' % (trainScore))
testScore = np.sqrt(mean_squared_error(test_set_scaled, predicted_stock_price))
print('Test Score: %.2f RMSE' % (testScore))

Test Score: 0.26 RMSE
